---
remote_theme: aksakalli/jekyll-doc-theme@gh-pages
title: APE Language
email: your-email@domain.com
description: APE programming language website
lang: en-US
url: https://ape-lang.org/
git_address: https://github.com/ApeLanguage/apelanguage.github.io
git_edit_address: https://github.com/ApeLanguage/apelanguage.github.io/blob/main
bootwatch: paper
markdown: kramdown
highlighter: rouge
plugins:
- jekyll-feed
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
exclude:
- Gemfile
- Gemfile.lock
- ".idea/"
- ".gitignore"
- README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog
- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: WebPage
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
  posts:
    permalink: "/blog/:year/:month/:day/:title/"
    output: true
