---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
sections:
- type: document
  path: _config.yml
  label: "\U0001F6E0 Jekyll Config"
- type: directory
  path: _data
  label: "\U0001F4E6 Data"
  create: all
  match: "**/*"
- type: directory
  path: _docs
  label: "\U0001F4DA Docs"
  create: all
  match: "**/*"
- type: document
  path: _data/docs.yml
  label: "\U0001F4D1 Docs Menu"
- type: jekyll-posts
  label: "✍ Posts"
  create: all
  templates:
  - blog-post
- type: jekyll-pages
  label: "\U0001F4C4 Pages"
  create: all
  templates:
  - page
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    -d _site
